---
- name: Install needed packages
  apt: pkg={{ item }} state=present
  with_items:
    - libcgi-fast-perl
    - fcgiwrap

- name: Fcgiwrap defaults file generation
  template:
    src=fcgiwrap.j2
    dest=/etc/default/fcgiwrap
  notify: Restart Fcgiwrap

- name: Fcgiwrap nginx configuration
  copy:
    src=fcgiwrap.conf
    dest=/etc/nginx/fcgiwrap.conf
