---
# tasks file for munin
- name: Pre-requirements
  apt: pkg={{ item }} state=present
  with_items:
    - python-pycurl

# For using cgi - i preffer versions  >=2.0.19
- name: Install munin package
  apt: pkg=munin,munin-common state=present

# TODO Pick one of the nginx roles and use it as dependency
- name: Install nginx package
  apt: pkg=nginx state=present

- name: Generate main configuration
  template:
      src=munin.conf.j2
      dest=/etc/munin/munin.conf
      owner=root
      group=munin
      mode=644

- name: Generate nginx target configuration
  template:
      src=nginx.conf.j2
      dest=/etc/munin/nginx.conf
      owner=root
      group=root
      mode=644
  notify: Reload nginx

- name: Create and chown directories
  include: directories.yml

- name: CGI mode configuration
  include: cgi.yml
  when: munin_cgi == True

- name: CGI mode cache configuration
  include: nginx_cache.yml
  when: munin_cgi_cache == True

- name: RRDCached configuration
  include: rrdcached.yml
  when: munin_rrdcached == True
